#!/usr/bin/env bash
# packaging/sea/build-sea.sh — turn a single-file CJS bundle into a Node SEA
# (single-executable-application) binary for one target platform, using the
# OFFICIAL nodejs.org prebuilt binary for that platform as the injection base
# (NOT whatever `node` happens to be on this machine's PATH — see the version-
# match note below).
#
# Usage:
#   build-sea.sh <bundle.cjs> <blob> <out-binary> <target-os> <target-arch> <node-version>
#
#   target-os:   darwin | linux | windows
#   target-arch: amd64  | arm64
#   node-version: e.g. v26.4.0 (MUST be the exact version used to generate <blob>
#                 — see build-all.sh. A blob generated by one Node version and
#                 injected into a binary of a DIFFERENT version silently no-ops
#                 at runtime: the SEA fuse looks flipped but the embedded main
#                 script never executes. Verified empirically 2026-07-06.)
#
# Requires: curl, tar (darwin/linux tarballs), unzip (windows zip), npx
# (for postject — fetched from the npm registry on first use and cached by
# npm itself), and on macOS, codesign (Xcode command line tools).
set -euo pipefail

BUNDLE="$1"; BLOB="$2"; OUT="$3"; TARGET_OS="$4"; TARGET_ARCH="$5"; NODE_VERSION="$6"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
CACHE_DIR="${THESUN_SEA_CACHE:-$SCRIPT_DIR/.cache}"
mkdir -p "$CACHE_DIR"

SENTINEL="NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2"

# ---- map thesun/Go-style os/arch to Node.js dist naming ----
case "$TARGET_OS" in
  darwin)  node_os="darwin" ;;
  linux)   node_os="linux" ;;
  windows) node_os="win" ;;
  *) echo "build-sea: unknown target-os '$TARGET_OS' (want darwin|linux|windows)" >&2; exit 2 ;;
esac
case "$TARGET_ARCH" in
  amd64) node_arch="x64" ;;
  arm64) node_arch="arm64" ;;
  *) echo "build-sea: unknown target-arch '$TARGET_ARCH' (want amd64|arm64)" >&2; exit 2 ;;
esac

archive_ext="tar.gz"
[ "$node_os" = "win" ] && archive_ext="zip"
dist_name="node-${NODE_VERSION}-${node_os}-${node_arch}"
archive_file="$CACHE_DIR/${dist_name}.${archive_ext}"
extract_dir="$CACHE_DIR/${dist_name}"

# ---- fetch + cache the official per-target Node runtime ----
if [ ! -d "$extract_dir" ]; then
  if [ ! -f "$archive_file" ]; then
    url="https://nodejs.org/dist/${NODE_VERSION}/${dist_name}.${archive_ext}"
    echo "build-sea: fetching $url"
    curl -fsSL -o "$archive_file" "$url"
  fi
  case "$archive_ext" in
    tar.gz) tar -xzf "$archive_file" -C "$CACHE_DIR" ;;
    zip)    unzip -q "$archive_file" -d "$CACHE_DIR" ;;
  esac
fi

if [ "$node_os" = "win" ]; then
  base_node="$extract_dir/node.exe"
else
  base_node="$extract_dir/bin/node"
fi
[ -f "$base_node" ] || { echo "build-sea: expected node binary at $base_node not found" >&2; exit 1; }

mkdir -p "$(dirname "$OUT")"
cp "$base_node" "$OUT"
chmod +w "$OUT"

# ---- macOS: strip the existing signature before mutating the Mach-O ----
if [ "$TARGET_OS" = "darwin" ]; then
  if command -v codesign >/dev/null 2>&1; then
    codesign --remove-signature "$OUT"
  else
    echo "build-sea: WARNING codesign not found — proceeding unsigned (macOS will refuse to run this binary as-is)" >&2
  fi
fi

# ---- inject the blob via postject (npx fetches+caches it on first use) ----
postject_args=(npx --yes postject "$OUT" NODE_SEA_BLOB "$BLOB" --sentinel-fuse "$SENTINEL" --overwrite)
if [ "$TARGET_OS" = "darwin" ]; then
  postject_args+=(--macho-segment-name NODE_SEA)
fi
"${postject_args[@]}"

# ---- macOS: re-sign ad-hoc (required for arm64 to execute at all; harmless
# on x64). This is NOT a distribution signature — operators running a
# downloaded macOS binary will still see an "unidentified developer" Gatekeeper
# prompt once via `xattr -d com.apple.quarantine` or right-click-Open. See
# docs/PACKAGING.md. ----
if [ "$TARGET_OS" = "darwin" ] && command -v codesign >/dev/null 2>&1; then
  codesign --sign - "$OUT"
fi

echo "build-sea: wrote $OUT ($TARGET_OS/$TARGET_ARCH, node $NODE_VERSION)"
